export const GET_FARMERS = "GET_FARMERS";
export const GET_FARMERS_SUCCESS = "GET_FARMERS_SUCCESS";
export const CREATE_FARMER = "CREATE_FARMER";
export const CREATE_FARMER_SUCCESS = "CREATE_FARMER_SUCCESS";
export const UPDATE_FARMER = "UPDATE_FARMER";
export const UPDATE_FARMER_SUCCESS = "UPDATE_FARMER_SUCCESS";
export const DELETE_FARMER = "UPDATE_FARMER";
export const DELETE_FARMER_SUCCESS = "UPDATE_FARMER_SUCCESS";
